config/routes.rb
Rails.application.routes.draw do

	root 'access#menu'
	get 'access/menu'
	get 'access/login'
	post 'access/attempt_login'
	get 'access/logout'
	get 'home/home_notification'
	get 'home/home_notification_show'
	get 'home/home_tag'
	get 'home/home_tag_show'
	post 'polls/add_option'
	get 'polls/delete_option'
	post '/polls/vote'
	post 'topics/add_post'
	post 'moderator_topics/add_moderator_post'
	post 'global_topics/add_global_post'
	post 'objective_questions/add_wrong_answer'
	get 'objective_questions/delete_wrong_answer'

	resources :towers do
		member do
			get :delete
		end
	end

	resources :moderators do
		member do
			get :delete
		end
	end

	resources :floors do
		member do
			get :delete
		end
	end

	resources :regulars do
		member do
			get :delete
		end
	end

	resources :notifications do
		member do
			get :delete
		end
	end

	resources :tags do
		member do
			get :delete
		end
	end

	resources :polls do
		member do
			get :delete
		end
	end

	resources :topics do
		member do
			get :delete
		end
	end

	resources :moderator_topics do
		member do
			get :delete
		end
	end

	resources :global_topics do
		member do
			get :delete
		end
	end

	resources :objective_tests do
		member do
			get :delete
		end
	end

	resources :objective_questions do
		member do
			get :delete
		end
	end

	resources :exams do
		member do
			get :delete
		end
	end

end

app/models/exam_record.rb
class ExamRecord < ApplicationRecord

	belongs_to :regular

end

app/models/floor.rb
class Floor < ApplicationRecord

	belongs_to :tower
	has_many :regulars, :dependent => :destroy
	has_many :notifications, :dependent => :destroy
	has_many :tags, :dependent => :destroy
	has_many :polls, :dependent => :destroy
	has_many :topics, :dependent => :destroy
	has_many :objective_tests, :dependent => :destroy

	validates_presence_of :floorname

end

app/models/global_post.rb
class GlobalPost < ApplicationRecord

	belongs_to :global_topic

end

app/models/global_topic.rb
class GlobalTopic < ApplicationRecord

	belongs_to :tower
	has_many :global_posts, :dependent => :destroy

end

app/models/moderator.rb
class Moderator < ApplicationRecord

	belongs_to :tower
	has_secure_password

	validates_presence_of :username

	def name
		"#{first_name} #{last_name}"
	end

end

app/models/notification.rb
class Notification < ApplicationRecord

	belongs_to :floor
	
end

app/models/option.rb
class Option < ApplicationRecord

	belongs_to :poll
	has_many :voters, :dependent => :destroy

end

app/models/poll.rb
class Poll < ApplicationRecord

	belongs_to :floor
	has_many :options, :dependent => :destroy

end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :topic

end

app/models/regular.rb
class Regular < ApplicationRecord

	belongs_to :floor
	belongs_to :tower
	has_many :exam_records
	has_secure_password

	validates_presence_of :username

	def name
		"#{first_name} #{last_name}"
	end

end

app/models/tag.rb
class Tag < ApplicationRecord

	belongs_to :floor

end

app/models/topic.rb
class Topic < ApplicationRecord

	belongs_to :floor
	has_many :posts, :dependent => :destroy

end

app/models/tower.rb
class Tower < ApplicationRecord

	has_many :moderators, :dependent => :destroy
	has_many :floors, :dependent => :destroy
	has_many :moderator_topics, :dependent => :destroy
	has_many :global_topics, :dependent => :destroy
	has_many :regulars, :dependent => :destroy

	has_secure_password

	validates_presence_of :towername, :password

	validates_uniqueness_of :towername

end

app/models/voter.rb
class Voter < ApplicationRecord

	belongs_to :option

end

app/models/wrong_answer.rb
class WrongAnswer < ApplicationRecord

	belongs_to :objective_question

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	before_action :confirm_logged_in
	before_action :is_regular

	# READ ACTIONS
	def index
		@floor = Floor.find(session[:floor_id])
		############################################################
		############SECURITY#########CHECK##########################
		if @floor.tower.id != session[:tower_id]
			redirect_to topics_path
			return
		end
		############################################################
		############################################################
		@topics = @floor.topics.order('topics.created_at DESC')
	end

	def show
		@topic = Topic.find(params[:id])
		############################################################
		############SECURITY#########CHECK##########################
		if @topic.floor.tower.id != session[:tower_id]
			redirect_to topics_path
			return
		end
		############################################################
		############################################################
		@posts = @topic.posts.order('posts.created_at DESC')
		@post = Post.new
	end

	def add_post
		@topic = Topic.find(params[:topic_id])
		############################################################
		############SECURITY#########CHECK##########################
		if @topic.floor.tower.id != session[:tower_id]
			redirect_to topics_path
			return
		end
		############################################################
		############################################################
		@post = Post.new(:message => params[:post][:message], :topic_id => @topic.id, :origin => session[:username])
		if @post.save
			redirect_to topic_path(@topic.id)
		else
			flash[:danger].now = "Post couldn't be created."
			render 'new'
		end
	end

	# CREATE ACTIONS
	def new
		@floor_id = session[:floor_id]
		@topic = Topic.new
	end

	def create
		@topic = Topic.new(:title => params[:topic][:title], :message => params[:topic][:message], :floor_id => session[:floor_id], :origin => session[:username])
		if @topic.save
			flash[:success] = "Topic created successfully."
			redirect_to topics_path(floor_id: @topic.floor)
		else
			flash[:danger].now = "Topic couldn't be created."
			render 'new'
		end
	end

	# UPDATE ACTIONS
	def edit
		@topic = Topic.find(params[:id])
		############################################################
		############SECURITY#########CHECK##########################
		if @topic.floor.tower.id != session[:tower_id]
			redirect_to topics_path
			return
		end
		############################################################
		############################################################
		@floor_id = @topic.floor.id
	end

	def update
		@topic = Topic.find(params[:id])
		############################################################
		############SECURITY#########CHECK##########################
		if @topic.floor.tower.id != session[:tower_id]
			redirect_to topics_path
			return
		end
		############################################################
		############################################################
		if @topic.update_attributes(topic_params)
			redirect_to topics_path(floor_id: @topic.floor)
		else
			render 'edit'
		end
	end

	# DELETE ACTIONS
	def delete
		@topic = Topic.find(params[:id])
		############################################################
		############SECURITY#########CHECK##########################
		if @topic.floor.tower.id != session[:tower_id]
			redirect_to topics_path
			return
		end
		############################################################
		############################################################
	end

	def destroy
		@topic = Topic.find(params[:id])
		############################################################
		############SECURITY#########CHECK##########################
		if @topic.floor.tower.id != session[:tower_id]
			redirect_to topics_path
			return
		end
		############################################################
		############################################################
		@topic.destroy
		flash[:success] = "Topic '#{@topic.title}' deleted successfully."
		redirect_to topics_path(floor_id: @topic.floor)
	end

	private

	def topic_params
		params.require(:topic).permit(:title, :message)
	end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/delete.html.erb
<% @page_title = "Delete Question"%>
<%= form_for(@topic,:method => 'delete') do |f| %>
<div class="center page-header">
  <h2><%= f.object.title %>?</h2>
</div>
    <div class="center form-group">
      <p>Are you sure you wish to permanently delete this?</p>
      <div class="col-sm-12">
        <%= f.submit "Delete Question",class: 'btn btn-danger btn-lg' %>
      </div>
    </div>
<% end %>

app/views/topics/edit.html.erb
<% @page_title = "Edit Question"%>
<div class="center page-header">
	<h2>Edit Question</h2>
</div>
<%= form_for(@topic,:url=> topic_path(@topic),:method => 'patch', :html => {:class => 'form-horizontal', :role => 'form'}) do |f| %>
<div class="form-group">
  <%= f.label :title, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter title', autofocus: true %>
  </div>
</div>
<div class="form-group">
	<%= f.label :message, class: 'col-sm-2 control-label' %>
	<div class="col-sm-8">
		<%= f.text_area :message,  rows: '7', class: 'form-control', placeholder: 'Enter message', autofocus: true %>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.submit "Update Question", class: 'btn btn-primary btn-lg' %>
	</div>
</div>
<% end %>

app/views/topics/index.html.erb
<% @page_title = "Local Forum" %>
<div class="center page-header">
  <h2>Local Forum</h2>
  <%= link_to("Ask Question", new_topic_path, :class => 'btn btn-primary') %>
</div>
<div class="col-xs-7 col-xs-offset-2">
 <% @topics.each do |topic| %>
 <div class="entry">
  <%= link_to(topic.title, topic_path(topic)) %>
  <p class="meta">
    <span class="date">
      <%= time_ago_in_words(topic.created_at) %> ago
    </span>
    <% if session[:username] != topic.origin %>
    <span>
      Posted by <%= topic.origin %>
    </span>
    <% end %>
    <% if session[:username] == topic.origin or session[:username] == "admin" %>
    <span>
      <%= link_to("Edit", edit_topic_path(topic)) %>
      <%= link_to("Delete", delete_topic_path(topic)) %>
    </span>
     <% end %>
  </p>
</div>
<% end %>
</div>

app/views/topics/new.html.erb
<% @page_title = "Ask Question" %>
<div class="center page-header">
	<h2>Ask Question</h2>
</div>
<%= form_for(@topic, :url=> topics_path, :method => 'post', :html => {:class => 'form-horizontal', :role => 'form'} ) do |f| %>
<div class="form-group">
  <%= f.label :title, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter title', autofocus: true %>
  </div>
</div>
<div class="form-group">
	<%= f.label :message, class: 'col-sm-2 control-label' %>
	<div class="col-sm-8">
		<%= f.text_area :message,  rows: '7', class: 'form-control', placeholder: 'Enter message', autofocus: true %>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.submit "Ask Question", class: 'btn btn-primary btn-lg' %>
	</div>
</div>
<% end %>

app/views/topics/show.html.erb
<% @page_title = "Local Forum" %>
<div class="center page-header">
  <h3><%= simple_format(@topic.message) %></h3>
</div>
<div class="col-xs-8 col-xs-offset-2">
<%= form_for(@post, :url=>  topics_add_post_path(@topic), :method => 'post', :html => {:class => 'form-horizontal', :role => 'form'} ) do |f| %>
<%= hidden_field_tag :topic_id, @topic.id %>
<div class="form-group">
  <%= f.submit "Post", class: 'btn btn-lg btn-primary' %>
  <div class="col-sm-8">
    <%= f.text_area :message,  rows: '1', class: 'form-control', placeholder: 'Say something helpful...', autofocus: true %>
  </div>
</div>
<% end %>
</div>
<div class="col-xs-8 col-xs-offset-2">
  <% @posts.each do |post| %>
  <div class="entry">
    <%= simple_format(post.message) %>
    <p class="meta">
    <span class="date">
      <%= time_ago_in_words(post.created_at) %> ago
    </span>
      Posted by <%= post.origin %>
    </p>
  </div>
  <% end %>
</div>