config/routes.rb
Rails.application.routes.draw do

	root 'access#menu'
	get 'access/menu'
	get 'access/login'
	post 'access/attempt_login'
	get 'access/logout'
	get 'home/home_notification'
	get 'home/home_notification_show'
	get 'home/home_tag'
	get 'home/home_tag_show'
	post 'polls/add_option'
	get 'polls/delete_option'
	post '/polls/vote'
	post 'topics/add_post'
	post 'moderator_topics/add_moderator_post'
	post 'global_topics/add_global_post'
	post 'objective_questions/add_wrong_answer'
	get 'objective_questions/delete_wrong_answer'

	resources :towers do
		member do
			get :delete
		end
	end

	resources :moderators do
		member do
			get :delete
		end
	end

	resources :floors do
		member do
			get :delete
		end
	end

	resources :regulars do
		member do
			get :delete
		end
	end

	resources :notifications do
		member do
			get :delete
		end
	end

	resources :tags do
		member do
			get :delete
		end
	end

	resources :polls do
		member do
			get :delete
		end
	end

	resources :topics do
		member do
			get :delete
		end
	end

	resources :moderator_topics do
		member do
			get :delete
		end
	end

	resources :global_topics do
		member do
			get :delete
		end
	end

	resources :objective_tests do
		member do
			get :delete
		end
	end

	resources :objective_questions do
		member do
			get :delete
		end
	end

	resources :exams do
		member do
			get :delete
		end
	end

end

app/models/exam_record.rb
class ExamRecord < ApplicationRecord

	belongs_to :regular

end

app/models/floor.rb
class Floor < ApplicationRecord

	belongs_to :tower
	has_many :regulars, :dependent => :destroy
	has_many :notifications, :dependent => :destroy
	has_many :tags, :dependent => :destroy
	has_many :polls, :dependent => :destroy
	has_many :topics, :dependent => :destroy
	has_many :objective_tests, :dependent => :destroy

	validates_presence_of :floorname

end

app/models/global_post.rb
class GlobalPost < ApplicationRecord

	belongs_to :global_topic

end

app/models/global_topic.rb
class GlobalTopic < ApplicationRecord

	belongs_to :tower
	has_many :global_posts, :dependent => :destroy

end

app/models/moderator.rb
class Moderator < ApplicationRecord

	belongs_to :tower
	has_secure_password

	validates_presence_of :username

	def name
		"#{first_name} #{last_name}"
	end

end

app/models/notification.rb
class Notification < ApplicationRecord

	belongs_to :floor
	
end

app/models/option.rb
class Option < ApplicationRecord

	belongs_to :poll
	has_many :voters, :dependent => :destroy

end

app/models/poll.rb
class Poll < ApplicationRecord

	belongs_to :floor
	has_many :options, :dependent => :destroy

end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :topic

end

app/models/regular.rb
class Regular < ApplicationRecord

	belongs_to :floor
	belongs_to :tower
	has_many :exam_records
	has_secure_password

	validates_presence_of :username

	def name
		"#{first_name} #{last_name}"
	end

end

app/models/tag.rb
class Tag < ApplicationRecord

	belongs_to :floor

end

app/models/topic.rb
class Topic < ApplicationRecord

	belongs_to :floor
	has_many :posts, :dependent => :destroy

end

app/models/tower.rb
class Tower < ApplicationRecord

	has_many :moderators, :dependent => :destroy
	has_many :floors, :dependent => :destroy
	has_many :moderator_topics, :dependent => :destroy
	has_many :global_topics, :dependent => :destroy
	has_many :regulars, :dependent => :destroy

	has_secure_password

	validates_presence_of :towername, :password

	validates_uniqueness_of :towername

end

app/models/voter.rb
class Voter < ApplicationRecord

	belongs_to :option

end

app/models/wrong_answer.rb
class WrongAnswer < ApplicationRecord

	belongs_to :objective_question

end

app/controllers/towers_controller.rb
class TowersController < ApplicationController

	before_action :confirm_logged_in, :except => [:new, :create]
	before_action :is_administrator, :except => [:new, :create]

	# READ ACTIONS
	def index
		redirect_to access_logout_path
	end

	def show
		@tower = Tower.find(session[:tower_id])
	end
	
	# CREATE ACTIONS
	def new
		@tower = Tower.new
	end

	def create
		@tower = Tower.new(:towername => params[:tower][:towername], :password => params[:tower][:password])
		if @tower.save
			flash[:success] = "Tower created successfully"
			redirect_to(access_login_path)
		else
			flash[:danger].now = "Tower couldn't be created."
			render 'new'
		end
	end

	# UPDATE ACTIONS
	def edit
		@tower = Tower.find(session[:tower_id])
	end

	def update
		@tower = Tower.find(session[:tower_id])
		if @tower.update_attributes(tower_params)
			redirect_to(access_login_path)
		else
			render 'edit'
		end
	end

	# DELETE ACTIONS
	def delete
		@tower = Tower.find(session[:tower_id])
	end

	def destroy
		@tower = Tower.find(session[:tower_id])
		@tower.destroy
		flash[:success] = "Tower '#{@tower.towername}' deleted successfully."
		redirect_to(access_login_path)
	end

	private

	def tower_params
		params.require(:tower).permit(:password)
	end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/towers_helper.rb
module TowersHelper
end

app/views/towers/delete.html.erb
<% @page_title = "Delete Tower"%>
<%= form_for(@tower,:method => 'delete') do |f| %>
<div class="center page-header">
  <h2><%= f.object.towername %>?</h2>
</div>
    <div class="center form-group">
      <p>Are you sure you wish to permanently delete this?</p>
      <div class="col-sm-12">
        <%= f.submit "Delete Tower",class: 'btn btn-danger btn-lg' %>
      </div>
    </div>
<% end %>

app/views/towers/edit.html.erb
<% @page_title = "Change Tower Password"%>
<div class="center page-header">
	<h2>Change Tower Password</h2>
</div>
<%= form_for(@tower,:url=> tower_path(@tower),:method => 'patch', :html => {:class => 'form-horizontal', :role => 'form'}) do |f| %>
<div class="form-group">
	<%= f.label :password, class: 'col-sm-2 control-label' %>
	<div class="col-sm-8">
		<%= f.text_field :password,  rows: '10', class: 'form-control', placeholder: 'Enter new password', autofocus: true %>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.submit "OK",class: 'btn btn-primary btn-lg' %>
	</div>
</div>
<% end %>

app/views/towers/new.html.erb
<% @page_title = "Register" %>
<div class="center page-header">
	<h2>Register</h2>
</div>
<%= form_for(@tower, :url=> towers_path, :method => 'post', :html => {:class => 'form-horizontal', :role => 'form'} ) do |f| %>
<div class="form-group">
	<%= f.label :towername, class: 'col-sm-2 control-label' %>
	<div class="col-sm-8">
		<%= f.text_field :towername,  rows: '10', class: 'form-control', placeholder: 'Your towername', autofocus: true %>
	</div>
</div>
<div class="form-group">
	<%= f.label :password, class: 'col-sm-2 control-label' %>
	<div class="col-sm-8">
		<%= f.text_field :password,  rows: '10', class: 'form-control', placeholder: 'Your password', autofocus: true %>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.submit "Register", class: 'btn btn-primary btn-lg' %>
	</div>
</div>
<% end %>
</div>

app/views/towers/show.html.erb
<div class="center page-header">
  <h2><%= @tower.towername %></h2>
  <%= link_to("Edit Tower", edit_tower_path(@tower.id), :class => 'btn btn-info') %>
  <%= link_to("Delete Tower", delete_tower_path(@tower.id), :class => 'btn btn-danger') %>
</div>