config/routes.rb
Rails.application.routes.draw do

	root 'access#menu'
	get 'access/menu'
	get 'access/login'
	post 'access/attempt_login'
	get 'access/logout'
	get 'home/home_notification'
	get 'home/home_notification_show'
	get 'home/home_tag'
	get 'home/home_tag_show'
	post 'polls/add_option'
	get 'polls/delete_option'
	post '/polls/vote'
	post 'topics/add_post'
	post 'moderator_topics/add_moderator_post'
	post 'global_topics/add_global_post'
	post 'objective_questions/add_wrong_answer'
	get 'objective_questions/delete_wrong_answer'

	resources :towers do
		member do
			get :delete
		end
	end

	resources :moderators do
		member do
			get :delete
		end
	end

	resources :floors do
		member do
			get :delete
		end
	end

	resources :regulars do
		member do
			get :delete
		end
	end

	resources :notifications do
		member do
			get :delete
		end
	end

	resources :tags do
		member do
			get :delete
		end
	end

	resources :polls do
		member do
			get :delete
		end
	end

	resources :topics do
		member do
			get :delete
		end
	end

	resources :moderator_topics do
		member do
			get :delete
		end
	end

	resources :global_topics do
		member do
			get :delete
		end
	end

	resources :objective_tests do
		member do
			get :delete
		end
	end

	resources :objective_questions do
		member do
			get :delete
		end
	end

	resources :exams do
		member do
			get :delete
		end
	end

end

app/models/exam_record.rb
class ExamRecord < ApplicationRecord

	belongs_to :regular

end

app/models/floor.rb
class Floor < ApplicationRecord

	belongs_to :tower
	has_many :regulars, :dependent => :destroy
	has_many :notifications, :dependent => :destroy
	has_many :tags, :dependent => :destroy
	has_many :polls, :dependent => :destroy
	has_many :topics, :dependent => :destroy
	has_many :objective_tests, :dependent => :destroy

	validates_presence_of :floorname

end

app/models/global_post.rb
class GlobalPost < ApplicationRecord

	belongs_to :global_topic

end

app/models/global_topic.rb
class GlobalTopic < ApplicationRecord

	belongs_to :tower
	has_many :global_posts, :dependent => :destroy

end

app/models/moderator.rb
class Moderator < ApplicationRecord

	belongs_to :tower
	has_secure_password

	validates_presence_of :username

	def name
		"#{first_name} #{last_name}"
	end

end

app/models/notification.rb
class Notification < ApplicationRecord

	belongs_to :floor
	
end

app/models/option.rb
class Option < ApplicationRecord

	belongs_to :poll
	has_many :voters, :dependent => :destroy

end

app/models/poll.rb
class Poll < ApplicationRecord

	belongs_to :floor
	has_many :options, :dependent => :destroy

end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :topic

end

app/models/regular.rb
class Regular < ApplicationRecord

	belongs_to :floor
	belongs_to :tower
	has_many :exam_records
	has_secure_password

	validates_presence_of :username

	def name
		"#{first_name} #{last_name}"
	end

end

app/models/tag.rb
class Tag < ApplicationRecord

	belongs_to :floor

end

app/models/topic.rb
class Topic < ApplicationRecord

	belongs_to :floor
	has_many :posts, :dependent => :destroy

end

app/models/tower.rb
class Tower < ApplicationRecord

	has_many :moderators, :dependent => :destroy
	has_many :floors, :dependent => :destroy
	has_many :moderator_topics, :dependent => :destroy
	has_many :global_topics, :dependent => :destroy
	has_many :regulars, :dependent => :destroy

	has_secure_password

	validates_presence_of :towername, :password

	validates_uniqueness_of :towername

end

app/models/voter.rb
class Voter < ApplicationRecord

	belongs_to :option

end

app/models/wrong_answer.rb
class WrongAnswer < ApplicationRecord

	belongs_to :objective_question

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

	before_action :confirm_logged_in
	before_action :is_not_regular
	
	# READ ACTIONS
	def index
		@floor = Floor.find(params[:floor_id])
		############################################################
		############SECURITY#########CHECK##########################
		if @floor.tower.id != session[:tower_id]
			redirect_to floors_path
			return
		end
		############################################################
		############################################################
		@floor_id = params[:floor_id]
		@notifications = @floor.notifications.order('notifications.created_at DESC')
	end

	def show
		@notification = Notification.find(params[:id])
		############################################################
		############SECURITY#########CHECK##########################
		if @notification.floor.tower.id != session[:tower_id]
			redirect_to floors_path
			return
		end
		############################################################
		############################################################
	end

	# CREATE ACTIONS
	def new
		@floor = Floor.find(params[:floor_id])
		############################################################
		############SECURITY#########CHECK##########################
		if @floor.tower.id != session[:tower_id]
			redirect_to floors_path
			return
		end
		############################################################
		############################################################
		@floor_id = @floor.id
		@notification = Notification.new
	end

	def create
		@floor = Floor.find(params[:floor_id])
		############################################################
		############SECURITY#########CHECK##########################
		if @floor.tower.id != session[:tower_id]
			redirect_to floors_path
			return
		end
		############################################################
		############################################################
		@notification = Notification.new(:title => params[:notification][:title], :message => params[:notification][:message], :floor_id => @floor.id, :origin => session[:username])
		if @notification.save
			flash[:success] = "Notification created successfully"
			redirect_to notifications_path(floor_id: @floor.id)
		else
			flash[:danger].now = "Notification couldn't be created."
			render 'new'
		end
	end

	# UPDATE ACTIONS
	def edit
		@floor = Floor.find(params[:floor_id])
		@notification = Notification.find(params[:id])
		############################################################
		############SECURITY#########CHECK##########################
		if @notification.floor.tower.id != session[:tower_id] or @notification.floor.id != @floor.id
			redirect_to floors_path
			return
		end
		############################################################
		############################################################
		@floor_id = @floor.id
	end

	def update
		@notification = Notification.find(params[:id])
		############################################################
		############SECURITY#########CHECK##########################
		if @notification.floor.tower.id != session[:tower_id]
			redirect_to floors_path
			return
		end
		############################################################
		############################################################
		if @notification.update_attributes(notification_params)
			redirect_to notifications_path(floor_id: @notification.floor.id)
		else
			render 'edit'
		end
	end

	# DELETE ACTIONS
	def delete
		@notification = Notification.find(params[:id])
		############################################################
		############SECURITY#########CHECK##########################
		if @notification.floor.tower.id != session[:tower_id]
			redirect_to floors_path
			return
		end
		############################################################
		############################################################
		@floor_id = @notification.floor.id
	end

	def destroy
		@notification = Notification.find(params[:id])
		############################################################
		############SECURITY#########CHECK##########################
		if @notification.floor.tower.id != session[:tower_id]
			redirect_to floors_path
			return
		end
		############################################################
		############################################################
		@notification.destroy
		flash[:success] = "Notification '#{@notification.title}' deleted successfully."
		redirect_to notifications_path(floor_id: @notification.floor.id)
	end

	private

	def notification_params
		params.require(:notification).permit(:title, :message)
	end
	
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/notifications/delete.html.erb
<% @page_title = "Delete Notification"%>
<%= form_for(@notification,:method => 'delete') do |f| %>
<%= hidden_field_tag :floor_id, @floor_id %>
<div class="center page-header">
  <h2><%= f.object.title %>?</h2>
</div>
    <div class="center form-group">
      <p>Are you sure you wish to permanently delete this?</p>
      <div class="col-sm-12">
        <%= f.submit "Delete Notification",class: 'btn btn-danger btn-lg' %>
      </div>
    </div>
<% end %>

app/views/notifications/edit.html.erb
<% @page_title = "Edit Notification"%>
<div class="center page-header">
	<h2>Edit Notification</h2>
</div>
<%= form_for(@notification,:url=> notification_path(@notification),:method => 'patch', :html => {:class => 'form-horizontal', :role => 'form'}) do |f| %>
<%= hidden_field_tag :floor_id, @floor_id %>
<div class="form-group">
  <%= f.label :title, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter title', autofocus: true %>
  </div>
</div>
<div class="form-group">
	<%= f.label :message, class: 'col-sm-2 control-label' %>
	<div class="col-sm-8">
		<%= f.text_area :message,  rows: '7', class: 'form-control', placeholder: 'Enter message', autofocus: true %>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.submit "Update",class: 'btn btn-primary btn-lg' %>
	</div>
</div>
<% end %>

app/views/notifications/index.html.erb
<% @page_title = "Notifications" %>
<div class="center page-header">
  <h2>Notifications for <%= @floor.floorname %></h2>
  <%= form_for(@floor, :url=> new_notification_path, :method => 'get' ) do |f| %>
  <%= hidden_field_tag :floor_id, @floor.id %>
  <%= f.submit "Add new Notification", class: 'btn btn-primary' %>
  <% end %>
</div>
<div class="col-xs-7 col-xs-offset-2">
  <% @notifications.each do |notification| %>
  <div class="entry">
   <%= link_to(notification.title, notification_path(notification)) %>
   <p class="meta">
    <table>
      <tr>
        <td>
          <%= form_for(@floor, :url=> edit_notification_path(notification), :method => 'get' ) do |f| %>
          <%= hidden_field_tag :floor_id, @floor.id %>
          <%= f.submit "Edit", class: 'btn btn-info' %>
          <% end %>
        </td>
        <td>&nbsp;</td>
        <td>
          <%= form_for(@floor, :url=> delete_notification_path(notification), :method => 'get' ) do |f| %>
          <%= hidden_field_tag :floor_id, @floor.id %>
          <%= f.submit "Delete", class: 'btn btn-danger' %>
          <% end %>
        </td>
        <td>&nbsp;&nbsp;&nbsp;</td>
        <td>
          <span>
            Added by <%= notification.origin %>
          </span>
        </td>
        <td>&nbsp;</td>
        <td>
          <span class="date">
           <%= time_ago_in_words(notification.created_at) %> ago
         </span>
       </td>
     </tr>
   </table>
 </p>
</div>
<% end %>
</div>

app/views/notifications/new.html.erb
<% @page_title = "Create Notification" %>
<div class="center page-header">
	<h2>Create Notification</h2>
</div>
<%= form_for(@notification, :url=> notifications_path, :method => 'post', :html => {:class => 'form-horizontal', :role => 'form'} ) do |f| %>
<%= hidden_field_tag :floor_id, @floor_id %>
<div class="form-group">
  <%= f.label :title, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter title', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :message, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_area :message,  rows: '7', class: 'form-control', placeholder: 'Enter message', autofocus: true %>
  </div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.submit "Create Notification", class: 'btn btn-primary btn-lg' %>
	</div>
</div>
<% end %>

app/views/notifications/show.html.erb
<% @page_title = "Notifications" %>
<div class="center page-header">
	<h2><%= @notification.title %></h2>
</div>
<div class="well col-xs-8 col-xs-offset-2">
  <p>
    <%= simple_format(@notification.message) %>
  </p>
</div>